---
version: '2.4'


services:


  db:
    image: mongo:4.2
    init: true
    restart: always
    networks:
      - ope
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ope
      - MONGO_INITDB_ROOT_PASSWORD=ope
    volumes:
      - ope_db_data:/data/db


  mongo_express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=ope
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ope
    networks:
      - ope
    depends_on:
      - db


  proxy:
    image: nginx:1.17-alpine
    restart: on-failure
    volumes:
      - ./proxy/nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - ope
    ports:
      - 9000:8080


  back:
    image: ope-dev:latest
    command: ["yarn", "workspace", "@ope/back", "run", "start"]
    init: true
    restart: on-failure
    environment:
      - MONGODB_URI
      - MONGODB_DB
      - ALLOWED_ORIGINS=localhost
    volumes:
      - .:/app:cached
    networks:
      - ope
    depends_on:
      - db


  front:
    image: ope-dev:latest
    command: ["yarn", "workspace", "@ope/front", "run", "start"]
    init: true
    stdin_open: true  # see https://github.com/facebook/create-react-app/issues/8688
    restart: on-failure
    volumes:
      - .:/app:cached
    networks:
      - ope
    depends_on:
      - back


networks:
  ope:
    name: ope


volumes:
  ope_db_data:
    name: ope_db_data
  yarn_cache:
    name: ope_yarn_cache
